# Generated by Django 2.2.5 on 2019-09-24 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('_parser', models.CharField(blank=True, editable=False, max_length=255)),
                ('user', models.ForeignKey(on_delete='delete', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'watch',
                'verbose_name_plural': 'watches',
            },
        ),
    ]
