# Generated by Django 2.2.5 on 2019-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwatcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
                ('description', models.TextField(verbose_name='description')),
                ('uid', models.CharField(max_length=255, verbose_name='unique id')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('watch', models.ForeignKey(on_delete='delete', to='webwatcher.Watch', verbose_name='watch')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
