# Generated by Django 2.2.5 on 2019-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwatcher', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
