# Generated by Django 2.2.5 on 2019-09-28 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webwatcher', '0004_auto_20190928_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='notification',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'instant'), (2, 'daily')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webwatcher.Watch', verbose_name='watch'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='periodic_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
