# Generated by Django 2.2.5 on 2019-09-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webwatcher", "0005_auto_20190928_2046")]

    operations = [
        migrations.AddField(
            model_name="item", name="notified", field=models.BooleanField(default=False)
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.CharField(max_length=255, null=True, verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="item",
            name="watch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="webwatcher.Watch",
                verbose_name="watch",
            ),
        ),
    ]
