# Generated by Django 2.2.5 on 2019-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwatcher', '0006_auto_20190928_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=512, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=512, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=512, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.CharField(max_length=512, verbose_name='unique id'),
        ),
    ]
